import { ScriptGenerationParams, OS } from "../types";

// Replaced Google GenAI with local template generation
const generateSystemScript = async (params: ScriptGenerationParams): Promise<string> => {
  // Simulate small delay for better UX feel
  await new Promise(resolve => setTimeout(resolve, 600));

  if (params.scriptType === 'python') {
    return generatePythonScript(params);
  } else {
    return generateShellScript(params);
  }
};

const generatePythonScript = (params: ScriptGenerationParams): string => {
  const { settings, cameraName } = params;
  const focusModeVal = settings.focusMode === 'continuous' ? 1 : 0;
  
  // Note: Different backends/cameras map properties differently.
  // We assume standard OpenCV CAP_PROP mappings.

  return `"""
Webcam Settings Persistence Script
Generated by FocusLock
---------------------------------
Camera: ${cameraName}
Target OS: ${params.os}

Prerequisites:
  pip install opencv-python

Compilation (to .exe for portability):
  1. pip install pyinstaller
  2. pyinstaller --onefile --noconsole script.py

Usage:
  Run this script on startup (e.g., via Task Scheduler) to enforce camera settings.
"""

import cv2
import time

def set_camera_settings():
    # Configuration
    # You may need to adjust the camera_index if you have multiple cameras
    camera_index = 0
    
    # Desired Settings
    FOCUS_AUTO = ${focusModeVal}  # 1=Auto, 0=Manual
    FOCUS_POS = ${settings.focusDistance}
    ZOOM = ${settings.zoom}
    BRIGHTNESS = ${settings.brightness}
    CONTRAST = ${settings.contrast}

    print(f"Initializing camera {camera_index}...")
    
    # Select backend based on OS
    backend = cv2.CAP_DSHOW if "${params.os}" == "Windows" else cv2.CAP_ANY
    cap = cv2.VideoCapture(camera_index, backend)
    
    if not cap.isOpened():
        # Fallback to default
        cap = cv2.VideoCapture(camera_index)
    
    if not cap.isOpened():
        print("Error: Could not open camera.")
        return

    # Allow camera to warm up
    time.sleep(0.5)

    print(f"Applying settings for: ${cameraName}")

    # 1. Autofocus
    # OpenCV Prop 39 = CAP_PROP_AUTOFOCUS
    print(f"Setting Autofocus to {FOCUS_AUTO}")
    cap.set(cv2.CAP_PROP_AUTOFOCUS, FOCUS_AUTO)
    
    # 2. Manual Focus
    # OpenCV Prop 28 = CAP_PROP_FOCUS
    if FOCUS_AUTO == 0:
        print(f"Setting Focus Distance to {FOCUS_POS}")
        cap.set(cv2.CAP_PROP_FOCUS, FOCUS_POS)

    # 3. Zoom
    # OpenCV Prop 27 = CAP_PROP_ZOOM
    print(f"Setting Zoom to {ZOOM}")
    cap.set(cv2.CAP_PROP_ZOOM, ZOOM)
    
    # 4. Brightness
    # OpenCV Prop 10 = CAP_PROP_BRIGHTNESS
    print(f"Setting Brightness to {BRIGHTNESS}")
    cap.set(cv2.CAP_PROP_BRIGHTNESS, BRIGHTNESS)
    
    # 5. Contrast
    # OpenCV Prop 11 = CAP_PROP_CONTRAST
    print(f"Setting Contrast to {CONTRAST}")
    cap.set(cv2.CAP_PROP_CONTRAST, CONTRAST)

    # Verification (Optional)
    actual_focus = cap.get(cv2.CAP_PROP_FOCUS)
    print(f"Settings applied. Current Focus State: {actual_focus}")

    cap.release()

if __name__ == "__main__":
    set_camera_settings()
`.trim();
};

const generateShellScript = (params: ScriptGenerationParams): string => {
  const { settings, os, cameraName } = params;

  if (os === OS.LINUX) {
    const focusAuto = settings.focusMode === 'continuous' ? 1 : 0;
    return `#!/bin/bash
# FocusLock - Webcam Settings Script
# Generated for: ${cameraName}

# Device path (Identify using: v4l2-ctl --list-devices)
DEVICE="/dev/video0"

# Dependency: v4l-utils (sudo apt-get install v4l-utils)

echo "Applying settings to $DEVICE..."

# 1. Auto Focus (0=Manual, 1=Auto)
# Note: Control names may vary by driver (e.g., focus_auto_continuous vs focus_auto)
v4l2-ctl -d $DEVICE --set-ctrl=focus_auto_continuous=${focusAuto} 2>/dev/null || v4l2-ctl -d $DEVICE --set-ctrl=focus_auto=${focusAuto}

# 2. Focus Distance (Only if Manual)
${focusAuto === 0 ? `v4l2-ctl -d $DEVICE --set-ctrl=focus_absolute=${settings.focusDistance}` : '# Manual focus skipped (Auto is On)'}

# 3. Zoom
v4l2-ctl -d $DEVICE --set-ctrl=zoom_absolute=${settings.zoom}

# 4. Brightness
v4l2-ctl -d $DEVICE --set-ctrl=brightness=${settings.brightness}

# 5. Contrast
v4l2-ctl -d $DEVICE --set-ctrl=contrast=${settings.contrast}

echo "Settings applied successfully."
`.trim();
  } 
  
  if (os === OS.MACOS) {
      return `#!/bin/bash
# MacOS Webcam Settings
# Generated for: ${cameraName}

# Requirements: 'uvc-control' (Install via: brew install uvc-control)
# Note: macOS restricts direct hardware access. This script is a template.

echo "Applying settings..."

# Syntax example (may require adjustment based on camera capabilities)
# uvc-control --set focus_auto=${settings.focusMode === 'continuous' ? 1 : 0}
# uvc-control --set focus_absolute=${settings.focusDistance}
# uvc-control --set zoom_absolute=${settings.zoom}

echo "Done."
`.trim();
  }

  // Windows PowerShell Fallback
  return `# PowerShell Webcam Settings
# Generated for: ${cameraName}

# NOTE: Windows does not provide built-in command-line tools for webcam properties.
#
# RECOMMENDATION: 
# Use the "Python" option in the Script Generator. 
# It produces a script that can be compiled to a .exe and runs reliably on Windows.

Write-Host "For reliable persistence on Windows, please select 'Python (Standalone)'."
Write-Host "That will generate a script using OpenCV which works natively on Windows."
Write-Host "You can then compile it to an EXE and place it in your Startup folder."

# If you have ffmpeg installed, you can try:
# ffmpeg -f dshow -i video="${cameraName}" -focus_mode ${settings.focusMode === 'continuous' ? 1 : 0} -t 0.1 -f null -
`.trim();
};

export { generateSystemScript };